name: Popa
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      
      - name: Say Hello
        run: echo "Hello"
      - name: Create folder
        run: mkdir POPOCHKA
      - name: Check pwd
        run:  |
          ls la
          pwd
      
      
